### ISSUE TITLE
Add Get It on F-Droid badge

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [tananaev/calculator-notification#18]
Since your app available on F-Droid as well, it’s reasonable to add the “Get It on F-Droid” badge on README.md, following instructions from their GitLab repository. And I suggest to host this badge on your website.
See: https://gitlab.com/fdroid/artwork/-/tree/master/badge

**Comment by DwainZwerg** [comment]
@tananaev You could close this issue as completed …
