### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [tananaev/calculator-notification#2]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, that do not use Google Play nor anything else, except F-Droid.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

Great app by the way 👍

**Comment by tananaev** [comment]
I don't mind including it in F-Droid, but unfortunately I don't have time to work on it. It would be great if someone else can do it.

**Comment by Poussinou** [comment]
Request For Packaging opened [here](https://gitlab.com/fdroid/rfp/issues/577).

**Comment by tananaev** [comment]
Great, thanks.

**Comment by Rudloff** [comment]
Hello,

We will need [tagged releases](https://help.github.com/articles/creating-releases/) in order to build the app for F-Droid.

**Comment by tananaev** [comment]
I have added a tag for last release.

**Comment by Rudloff** [comment]
I think this can be closed.
