### ISSUE TITLE
stops working on Oreo after a while

### ISSUE THREAD

**Issue by hmueller01** [tananaev/calculator-notification#5]
Calculator notification stops working after some time. It's still shown in notification but all button presses are not recognized. Stopping and restarting makes it work again for some time. Tested with Oreo 8.0 and 8.1. Maybe this is an issue with the [Background Execution Limits on Android Oreo](https://medium.com/exploring-android/exploring-background-execution-limits-on-android-oreo-ab384762a66c).

**Comment by hmueller01** [comment]
Ok, more details. The MainApplication will obviously be destroyed and `notificationManager` and `notificationBuilder`get `null` in `handleClick(int buttonId)`. Any ideas how to solve that?

**Comment by hmueller01** [comment]
Ok, only `notificationBuilder` is `null`. So it looks like MainApplication gets destroyed and afterwards restored with the broadcast by calling the `onCreate()`. If I call `showNotification()` there it works, except that the old input (`value`) gets erased. I am not sure about the BackgroundService you start. Maybe it was done to keep the Application alive. But this does not work with Oreo any more ...

**Comment by tananaev** [comment]
Yes, the idea behind the service is to keep app running. I guess now we need to make it foreground service.

**Comment by hmueller01** [comment]
Ok, I changed the code to use a foreground service. You may test [my fork](https://github.com/hmueller01/calculator-notification/tree/oreo-fixes).

**Comment by tananaev** [comment]
Does it work now? If yes, we can merge it into the official app. Probably some minor changes in the code would be required.

**Comment by hmueller01** [comment]
Yes, it works with 8.1, 8.0, 7.1.2, 4.1.2. But with the foreground service the calculator can not be swiped away to stop it (it looks like it implies setOngoing(true)). On pre Nougat the tiles are not available. So there is no easy way to stop the calculator. It is only possible using App-Info and force stop. Maybe solution #1 is most feasible right now.

Update: Even setting setOngoing(false) makes no difference.
Should I make a pull request anyway?

**Comment by tananaev** [comment]
What if we store last know value somewhere? For example in preferences?

**Comment by hmueller01** [comment]
In deed, this was my idea in the first place. I am not very happy with the foreground service that somethings running permanently in background without having Android a chance to remove it from RAM. Do you have time to implement that? Otherwise I can try it in the next few days ...

**Comment by tananaev** [comment]
Unfortunately I don't have time at the moment.

**Comment by hmueller01** [comment]
If you be so kind and merge my pull requests I'd like to add a preference plane to enable/disable the setOngoing(true). Thanks.

**Comment by tananaev** [comment]
Merged and published a new release. Thanks for pull requests.

**Comment by hmueller01** [comment]
Thanks for all the optimizations you made.
But too bad, that you removed the comment in the if statement
```
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            // keep application alive with a background service works only on pre Oreo
```
In a year I am sure that I can not remember why the service is only started on pre Oreo ...
Ok, the if is not really necessary but I thought if the service is useless there is no need to start it.

**Comment by tananaev** [comment]
Actually I think we shouldn't have that check at all. Oreo has services as well.

**Comment by hmueller01** [comment]
On the other hand, do we need the service at all, as the new solution works on all variants of Android ...

**Comment by tananaev** [comment]
I think it will be better with service. Without service Android will re-start app every time. With service it will likely stay alive, as least for some period of time without restarts.

**Comment by hmueller01** [comment]
Ok, on devices with Nougat and before the app is never killed with the background service. Since Oreo it makes no difference (based on the experience with my device). But ok, the if statement can also be dropped. Thanks for discussing. :-)
